/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.awt.AWTUtilities;
import excepciones.LoteLlenoException;
import excepciones.PesebreraLlenaException;
import excepciones.PocilgaLlenaException;
import java.awt.Frame;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import modelo.Animal;
import modelo.Bovino;
import modelo.Equino;
import modelo.Porcino;
import modelo.pila.AccionRealizadaAnimal;

/**
 *
 * @author andre
 */
public class VistaSelect extends javax.swing.JFrame {

    VistaHome vistaHome;
    int numeroTerreno;
    int fila;
    int columna;

    /**
     * Creates new form VistaSelect
     */
    public VistaSelect(VistaHome vistaHome, int numeroTerreno, int fila, int columna) {
        initComponents();
        setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);
        this.vistaHome = vistaHome;
        if (vistaHome.terreno.equals(vistaHome.LOTE)) {
            btnMachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/macho.png")));
            btnMachos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/macho_Pressed.png")));
            btnHembras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/hembra.png")));
            btnHembras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/hembra_Pressed.png")));
        } else if (vistaHome.terreno.equals(vistaHome.PESEBRERA)) {
            btnMachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/macho.png")));
            btnMachos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/macho_Pressed.png")));
            btnHembras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/hembra.png")));
            btnHembras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/hembra_Pressed.png")));
        } else if (vistaHome.terreno.equals(vistaHome.POCILGA)) {
            btnMachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/macho.png")));
            btnMachos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/macho_Pressed.png")));
            btnHembras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/hembra.png")));
            btnHembras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/hembra_Pressed.png")));
        }
        this.numeroTerreno = numeroTerreno;
        this.fila = fila;
        this.columna = columna;
    }

    public void mostrarMensaje(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.ERROR_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoBlack_Pequeño.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        btnMachos = new javax.swing.JButton();
        btnHembras = new javax.swing.JButton();
        titulo3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        crias1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Duralith", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Seleccione");
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, -1));

        titulo2.setFont(new java.awt.Font("Duralith", 0, 18)); // NOI18N
        titulo2.setForeground(new java.awt.Color(0, 0, 0));
        titulo2.setText("Machos");
        titulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, -1));

        btnMachos.setBackground(new java.awt.Color(255, 255, 255));
        btnMachos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachosActionPerformed(evt);
            }
        });
        jPanel1.add(btnMachos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 95, 95));

        btnHembras.setBackground(new java.awt.Color(255, 255, 255));
        btnHembras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHembras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHembrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnHembras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 95, 95));

        titulo3.setFont(new java.awt.Font("Duralith", 0, 18)); // NOI18N
        titulo3.setForeground(new java.awt.Color(0, 0, 0));
        titulo3.setText("Hembras");
        titulo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoBlack_Pequeño.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolverDos.png"))); // NOI18N
        btnVolver.setToolTipText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolverPressedDos.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        crias1.setFont(new java.awt.Font("Duralith", 0, 18)); // NOI18N
        crias1.setForeground(new java.awt.Color(0, 0, 0));
        crias1.setText("VS");
        crias1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(crias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 30, -1));

        jLabel2.setFont(new java.awt.Font("Duralith", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Al seleccionar, se registrará un animal automáticamente.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCerrar.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCerrar_Click.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnMinimizar.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnMinimizar_Click.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VistaTerreno vistaTerreno = new VistaTerreno(vistaHome);
        vistaTerreno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnMachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMachosActionPerformed
        try {
            int size = vistaHome.getControladorTerreno().getSize();
            size++;
            if (vistaHome.terreno.equals(vistaHome.LOTE)) {
                Bovino bovino = new Bovino(Bovino.MACHO, size, numeroTerreno);
                vistaHome.getControladorTerreno().añadirAnimal(fila, columna, vistaHome.LOTE, bovino, false);
                AccionRealizadaAnimal action = new AccionRealizadaAnimal(bovino, AccionRealizadaAnimal.actionRegistrar, fila, columna);
                vistaHome.getControladorPila().pushAnimalAction(action);
                vistaHome.cantidadAction++;
                vistaHome.getControladorTerreno().asignarSexoTerreno(fila, columna, 2, vistaHome.LOTE);
                vistaHome.getControladorTerreno().cambiarEstadoTerreno(fila, columna, 3, vistaHome.LOTE);
            } else if (vistaHome.terreno.equals(vistaHome.PESEBRERA)) {
                Equino equino = new Equino(false, numeroTerreno, Equino.MACHO, size);
                vistaHome.getControladorTerreno().añadirAnimal(fila, columna, vistaHome.PESEBRERA, equino, false);
                AccionRealizadaAnimal action = new AccionRealizadaAnimal(equino, AccionRealizadaAnimal.actionRegistrar, fila, columna);
                vistaHome.getControladorPila().pushAnimalAction(action);
                vistaHome.getControladorTerreno().asignarSexoTerreno(fila, columna, 2, vistaHome.PESEBRERA);
                vistaHome.getControladorTerreno().cambiarEstadoTerreno(fila, columna, 3, vistaHome.PESEBRERA);
            } else {
                Porcino porcino = new Porcino(false, numeroTerreno, Equino.MACHO, size);
                vistaHome.getControladorTerreno().añadirAnimal(fila, columna, vistaHome.POCILGA, porcino, false);
                AccionRealizadaAnimal action = new AccionRealizadaAnimal(porcino, AccionRealizadaAnimal.actionRegistrar, fila, columna);
                vistaHome.getControladorPila().pushAnimalAction(action);
                vistaHome.getControladorTerreno().asignarSexoTerreno(fila, columna, 2, vistaHome.POCILGA);
                vistaHome.getControladorTerreno().cambiarEstadoTerreno(fila, columna, 3, vistaHome.POCILGA);
            }
            VistaGestionAnimales vistaGestionAnimales = new VistaGestionAnimales(vistaHome, numeroTerreno, fila, columna);
            vistaGestionAnimales.setVisible(true);
            this.dispose();
        } catch (LoteLlenoException | PesebreraLlenaException | PocilgaLlenaException ex) {
            mostrarMensaje(ex.getMessage(), "Error");
        }
    }//GEN-LAST:event_btnMachosActionPerformed

    private void btnHembrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHembrasActionPerformed
        try {
            int size = vistaHome.getControladorTerreno().getSize();
            size++;
            if (vistaHome.terreno.equals(vistaHome.LOTE)) {
                Bovino bovino = new Bovino(Bovino.HEMBRA, size, numeroTerreno);
                vistaHome.getControladorTerreno().añadirAnimal(fila, columna, vistaHome.LOTE, bovino, false);
                AccionRealizadaAnimal action = new AccionRealizadaAnimal(bovino, AccionRealizadaAnimal.actionRegistrar, fila, columna);
                vistaHome.getControladorPila().pushAnimalAction(action);
                vistaHome.getControladorTerreno().asignarSexoTerreno(fila, columna, 1, vistaHome.LOTE);
                vistaHome.getControladorTerreno().cambiarEstadoTerreno(fila, columna, 3, vistaHome.LOTE);
            } else if (vistaHome.terreno.equals(vistaHome.PESEBRERA)) {
                Equino equino = new Equino(false, numeroTerreno, Equino.HEMBRA, size);
                vistaHome.getControladorTerreno().añadirAnimal(fila, columna, vistaHome.PESEBRERA, equino, false);
                AccionRealizadaAnimal action = new AccionRealizadaAnimal(equino, AccionRealizadaAnimal.actionRegistrar, fila, columna);
                vistaHome.getControladorPila().pushAnimalAction(action);
                vistaHome.getControladorTerreno().asignarSexoTerreno(fila, columna, 1, vistaHome.PESEBRERA);
                vistaHome.getControladorTerreno().cambiarEstadoTerreno(fila, columna, 3, vistaHome.PESEBRERA);
            } else {
                Porcino porcino = new Porcino(false, numeroTerreno, Equino.HEMBRA, size);
                vistaHome.getControladorTerreno().añadirAnimal(fila, columna, vistaHome.POCILGA, porcino, false);
                vistaHome.getControladorTerreno().asignarSexoTerreno(fila, columna, 1, vistaHome.POCILGA);
                vistaHome.getControladorTerreno().cambiarEstadoTerreno(fila, columna, 3, vistaHome.POCILGA);
            }
            VistaGestionAnimales vistaGestionAnimales = new VistaGestionAnimales(vistaHome, numeroTerreno, fila, columna);
            vistaGestionAnimales.setVisible(true);
            this.dispose();
        } catch (LoteLlenoException | PesebreraLlenaException | PocilgaLlenaException ex) {
            mostrarMensaje(ex.getMessage(), "Error");
        }
    }//GEN-LAST:event_btnHembrasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaSelect().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHembras;
    private javax.swing.JButton btnMachos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel crias1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables
}
