/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.awt.AWTUtilities;
import excepciones.CampoVacioException;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import modelo.Animal;
import modelo.CuidadoEquino;
import modelo.Premio;
import modelo.pila.AccionRealizadaCuidado;
import modelo.pila.AccionRealizadaPremio;

/**
 *
 * @author andre
 */
public class VistaFormularioPremioCuidado extends javax.swing.JDialog {

    VistaHome vistaHome;
    int codigoAnimal;
    int desicion;

    /**
     * Creates new form VistaFormularioPremio
     */
    public VistaFormularioPremioCuidado(java.awt.Frame parent, boolean modal, VistaHome vistaHome, int codigoAnimal, int desicion) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);
        this.vistaHome = vistaHome;
        this.codigoAnimal = codigoAnimal;
        this.desicion = desicion;
        if (desicion == 0) {
            titulo.setText("Registro de Premios");
            txtTitulo.setText("Título del Premio");
            jcbTipo.setVisible(true);
        } else {
            titulo.setText("Registro de Cuidados");
            txtTitulo.setText("Título del Cuidado");
            jcbTipo.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        jcbYear = new javax.swing.JComboBox<>();
        jcbTipo = new javax.swing.JComboBox<>();
        titulo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtTitulo.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setText("Título del Premio");
        txtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTituloMouseClicked(evt);
            }
        });
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, 30));

        jcbYear.setBackground(new java.awt.Color(255, 255, 255));
        jcbYear.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        jcbYear.setForeground(new java.awt.Color(0, 0, 0));
        jcbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Año", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));
        jPanel1.add(jcbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, 30));

        jcbTipo.setBackground(new java.awt.Color(255, 255, 255));
        jcbTipo.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        jcbTipo.setForeground(new java.awt.Color(0, 0, 0));
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo", "Deportivo", "Cultural", "Intelectual" }));
        jPanel1.add(jcbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 170, 30));

        titulo.setFont(new java.awt.Font("Duralith", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Registro de Premios");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnFondoDark.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnFondoDark_Pressed.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 110, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfaz_Eliminar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            if (desicion == 0) {
                if (txtTitulo.getText().isEmpty() || jcbTipo.getSelectedIndex() == 0 || jcbYear.getSelectedIndex() == 0
                        || txtTitulo.getText().equals("Título del Premio")) {
                    throw new CampoVacioException();
                }
                String titulo = txtTitulo.getText();
                String tipo = jcbTipo.getSelectedItem().toString();
                String year = jcbYear.getSelectedItem().toString();
                int codigoEquino = codigoAnimal;
                Premio premio = new Premio(codigoEquino, tipo, titulo, year);
                vistaHome.getControladorDPC().añadirPremio(premio);
                AccionRealizadaPremio accion = new AccionRealizadaPremio(premio, AccionRealizadaPremio.actionRegistrar);
                vistaHome.getControladorPila().pushPremioAction(accion);
                mostrarMensaje("Premio registrado Correctamente", "Operación Exitosa");
                this.dispose();
            } else {
                if (txtTitulo.getText().isEmpty() || jcbYear.getSelectedIndex() == 0
                        || txtTitulo.getText().equals("Título del Premio")) {
                    throw new CampoVacioException();
                }
                String cuidadoRealizado = txtTitulo.getText();
                String year = jcbYear.getSelectedItem().toString();
                int codigoEquino = codigoAnimal;
                CuidadoEquino cuidadoEquino = new CuidadoEquino(codigoEquino, cuidadoRealizado, year);
                vistaHome.getControladorDPC().añadirCuidado(cuidadoEquino);
                AccionRealizadaCuidado accion = new AccionRealizadaCuidado(cuidadoEquino, AccionRealizadaCuidado.actionRegistrar);
                vistaHome.getControladorPila().pushCuidadoAction(accion);;
                mostrarMensaje("Cuidado registrado Corretamente", "Operación Exitosa");
                this.dispose();
            }
        } catch (CampoVacioException ex) {
            mostrarMensaje(ex.getMessage(), "Error");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTituloMouseClicked
        txtTitulo.setText("");
    }//GEN-LAST:event_txtTituloMouseClicked

    public void mostrarMensaje(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.ERROR_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoBlack_Pequeño.png")));
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioPremioCuidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioPremioCuidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioPremioCuidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioPremioCuidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaFormularioPremioCuidado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JComboBox<String> jcbYear;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
