/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.awt.AWTUtilities;
import excepciones.CampoVacioException;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import modelo.Bovino;
import modelo.Equino;
import modelo.Lote;
import modelo.Pesebrera;
import modelo.Pocilga;
import modelo.Porcino;
import modelo.Terreno;

/**
 *
 * @author andre
 */
public class VistaTerreno extends javax.swing.JFrame implements ActionListener {

    JButton[][] botones;
    VistaHome vistaHome;

    /**
     * Creates new form VistaLotes
     */
    public VistaTerreno(VistaHome vistaHome) {
        initComponents();
        setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);
        this.vistaHome = vistaHome;
        txtValorxKilo.setText(String.valueOf(Terreno.getValorxKilo()));
        if (vistaHome.terreno.equals(vistaHome.LOTE)) {
            labelCamino.setVisible(false);
            titulo.setText("Lotes (Bovinos)");
            icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/bovinos.png")));
            botones = new JButton[3][4];
            cargarBotonesLotes();
            validarBotonesLotes();
        } else if (vistaHome.terreno.equals(vistaHome.PESEBRERA)) {
            titulo.setText("Pesebreras (Equinos)");
            icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/equino.png")));
            botones = new JButton[4][6];
            cargarBotonesPesebreras();
            validarBotonesPesebreras();
        } else if (vistaHome.terreno.equals(vistaHome.POCILGA)) {
            titulo.setText("Pocilgas (Porcinos)");
            icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/porcino.png")));
            labelCamino.setVisible(false);
            botones = new JButton[2][8];
            cargarBotonesPocilgas();
            validarBotonesPocilgas();
        }
        this.vistaHome = vistaHome;
        if (vistaHome.ID_Login == vistaHome.ADMINISTRADOR) {
            btnVolver.setVisible(true);
            btnSalir.setVisible(false);
        } else {
            btnVolver.setVisible(false);
            btnSalir.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPredio = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        labelCamino = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEliminaciones = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        txtValorxKilo = new javax.swing.JTextField();
        btnActualizarValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPredio.setBackground(new java.awt.Color(255, 255, 255));
        panelPredio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCamino.setBackground(new java.awt.Color(0, 0, 0));
        labelCamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/caminoPiedra.png"))); // NOI18N

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelCamino, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(labelCamino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        panelPredio.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 440, 340));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCerrar.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCerrar_Click.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnMinimizar.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnMinimizar_Click.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 475, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPredio.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 20));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSalirPressedDos.png"))); // NOI18N
        btnSalir.setToolTipText("Cerrar Sesión");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSalirDos.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelPredio.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolverDos.png"))); // NOI18N
        btnVolver.setToolTipText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolverPressedDos.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelPredio.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        titulo.setFont(new java.awt.Font("Duralith", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Lotes (Bovinos) ");
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelPredio.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, -1));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lote/bovinos.png"))); // NOI18N
        icono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelPredio.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoBlack_Pequeño.png"))); // NOI18N
        panelPredio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Valor x Kilo");
        panelPredio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        btnEliminaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEliminados.png"))); // NOI18N
        btnEliminaciones.setToolTipText("Registro de Eliminados");
        btnEliminaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminaciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEliminados_Pressed.png"))); // NOI18N
        btnEliminaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminacionesActionPerformed(evt);
            }
        });
        panelPredio.add(btnEliminaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 40, 40));

        btnVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVender.png"))); // NOI18N
        btnVentas.setToolTipText("Registro de Ventas");
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVender_Pressed.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        panelPredio.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 40, 40));

        txtValorxKilo.setBackground(new java.awt.Color(255, 255, 255));
        txtValorxKilo.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        txtValorxKilo.setForeground(new java.awt.Color(0, 0, 0));
        txtValorxKilo.setText("14000");
        panelPredio.add(txtValorxKilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 60, -1));

        btnActualizarValor.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarValorActionPerformed(evt);
            }
        });
        panelPredio.add(btnActualizarValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 20, 20));

        getContentPane().add(panelPredio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VistaAdmin vistaAdmin = new VistaAdmin(vistaHome);
        vistaAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        vistaHome.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked

    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnEliminacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminacionesActionPerformed
        VistaInformativa vistaVYE = new VistaInformativa(vistaHome, 0, 0, false, 0, 0, 0);
        vistaVYE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminacionesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        VistaInformativa vistaVYE = new VistaInformativa(vistaHome, 1, 0, false, 0, 0, 0);
        vistaVYE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnActualizarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarValorActionPerformed
        try {
            if (txtValorxKilo.getText().isEmpty() || txtValorxKilo.getText().equals("")) {
                throw new CampoVacioException();
            }
            double valorxKilo = Double.parseDouble(txtValorxKilo.getText());
            Terreno.setValorxKilo(valorxKilo);
            txtValorxKilo.setText(String.valueOf(Terreno.getValorxKilo()));
            mostrarMensaje("Valor x Kilo Actualizado", "Information");
        } catch (CampoVacioException ex) {
            mostrarMensaje(ex.getMessage(), "error");
        }
    }//GEN-LAST:event_btnActualizarValorActionPerformed

    public void mostrarMensaje(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.ERROR_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoBlack_Pequeño.png")));
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaTerreno().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarValor;
    private javax.swing.JButton btnEliminaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCamino;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPredio;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtValorxKilo;
    // End of variables declaration//GEN-END:variables

    private void cargarBotonesLotes() {
        int ancho = 100;
        int alto = 100;
        int separado = 20;
        int numeroLote = 1;
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                //setBounds(posX, posY, ancho, alto)
                botones[i][j].setBounds((j * ancho + separado), (i * alto + separado), ancho, alto);
                botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/fondoLote.png")));
                botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/fondoLotePressed.jpg")));
                botones[i][j].setText(String.valueOf(numeroLote));
                botones[i][j].setHorizontalTextPosition(SwingConstants.CENTER);
                botones[i][j].setVerticalTextPosition(SwingConstants.CENTER);
                botones[i][j].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                botones[i][j].addActionListener(this);
                botones[i][j].setBackground(Color.GREEN);
                botones[i][j].setForeground(Color.white);
                panelBotones.add(botones[i][j]);
                numeroLote++;
            }
        }
    }

    public void validarBotonesLotes() {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                Lote lote = vistaHome.getControladorTerreno().obtenerLote(i, j);
                if (lote.getCantidadBovinos() > 0 && lote.getSexoAnimales().equals(Bovino.MACHO)) {
                    botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/LoteToro.png")));
                    botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/LoteToro_Pressed.png")));
                } else if (lote.getCantidadBovinos() > 0 && lote.getSexoAnimales().equals(Bovino.HEMBRA)) {
                    botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/LoteVaca.png")));
                    botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lote/LoteVaca_Pressed.png")));
                }
            }
        }
    }

    private void cargarBotonesPesebreras() {
        int ancho = 65;
        int alto = 65;
        int separado = 20;
        int separadoDos = 62;
        int numeroPesebrera = 1;
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                //setBounds(posX, posY, ancho, alto)
                if (numeroPesebrera >= 13 && numeroPesebrera <= 24) {
                    botones[i][j].setBounds((j * ancho + separado), (i * alto + separadoDos), ancho, alto);
                } else {
                    botones[i][j].setBounds((j * ancho + separado), (i * alto + separado), ancho, alto);
                }
                botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/PesebreraFondo.png")));
                botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/PesebreraFondoPressed.png")));
                botones[i][j].setText(String.valueOf(numeroPesebrera));
                botones[i][j].setHorizontalTextPosition(SwingConstants.CENTER);
                botones[i][j].setVerticalTextPosition(SwingConstants.CENTER);
                botones[i][j].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                botones[i][j].addActionListener(this);
                botones[i][j].setForeground(Color.white);
                panelBotones.add(botones[i][j]);
                numeroPesebrera++;
            }
        }
    }

    public void validarBotonesPesebreras() {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                Pesebrera pesebrera = vistaHome.getControladorTerreno().obtenerPesebrera(i, j);
                if (pesebrera.getCantidadEquinos() > 0 && pesebrera.getSexoAnimales().equals(Equino.MACHO)) {
                    botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/PesebreraCaballo.png")));
                    botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/PesebreraCaballo_Pressed.png")));
                } else if (pesebrera.getCantidadEquinos() > 0 && pesebrera.getSexoAnimales().equals(Equino.HEMBRA)) {
                    botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/PesebreraYegua.png")));
                    botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pesebrera/PesebreraYegua_Pressed.png")));
                }
            }
        }
    }

    private void cargarBotonesPocilgas() {
        int ancho = 45;
        int alto = 80;
        int separado = 80;
        int separadoDos = 20;
        int separadoTres = 60;
        int numeroPocilga = 1;
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                //setBounds(posX, posY, ancho, alto)
                if (numeroPocilga >= 5 && numeroPocilga <= 8 || (numeroPocilga >= 13 && numeroPocilga <= 16)) {
                    botones[i][j].setBounds((j * ancho + separadoTres), (i * alto + separado), ancho, alto);
                } else {
                    botones[i][j].setBounds((j * ancho + separadoDos), (i * alto + separado), ancho, alto);
                }
                botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/pocilgaFondo.png")));
                botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/pocilgaFondoPressed.png")));
                botones[i][j].setText(String.valueOf(numeroPocilga));
                botones[i][j].setHorizontalTextPosition(SwingConstants.CENTER);
                botones[i][j].setVerticalTextPosition(SwingConstants.CENTER);
                botones[i][j].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                botones[i][j].addActionListener(this);
                botones[i][j].setForeground(Color.white);
                panelBotones.add(botones[i][j]);
                numeroPocilga++;
            }
        }
    }

    public void validarBotonesPocilgas() {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                Pocilga pocilga = vistaHome.getControladorTerreno().obtenerPocilga(i, j);
                if (pocilga.getCantidadPorcinos() > 0) {
                    botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/PocilgaCerda.png")));
                    botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/PocilgaCerda_Pressed.png")));
                }
                if (pocilga.getCantidadPorcinos() > 0 && pocilga.isCrias()) {
                    botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/PocilgaCerdito.png")));
                    botones[i][j].setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pocilga/PocilgaCerdito_Pressed.png")));
                }
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                if (ae.getSource().equals(botones[i][j])) {
                    if (vistaHome.terreno.equals(vistaHome.LOTE)) {
                        Lote lote = vistaHome.getControladorTerreno().obtenerLote(i, j);
                        if (lote.getEstado().equals(Lote.VACIO)) {
                            vistaHome.numeroTerreno = lote.getNumero();
                            VistaSelect vistaSelect = new VistaSelect(vistaHome, lote.getNumero(), i, j);
                            vistaSelect.setVisible(true);
                            this.dispose();
                        } else {
                            VistaGestionAnimales vistaGestionAnimales = new VistaGestionAnimales(vistaHome, lote.getNumero(), i, j);
                            vistaGestionAnimales.setVisible(true);
                            this.dispose();
                        }
                    } else if (vistaHome.terreno.equals(vistaHome.POCILGA)) {
                        Pocilga pocilga = vistaHome.getControladorTerreno().obtenerPocilga(i, j);
                        VistaGestionAnimales vistaGestionAnimales = new VistaGestionAnimales(vistaHome, pocilga.getNumero(), i, j);
                        vistaGestionAnimales.setVisible(true);
                        this.dispose();
                    } else if (vistaHome.terreno.equals(vistaHome.PESEBRERA)) {
                        Pesebrera pesebrera = vistaHome.getControladorTerreno().obtenerPesebrera(i, j);
                        if (pesebrera.getEstado().equals(Pesebrera.VACIO)) {
                            vistaHome.numeroTerreno = pesebrera.getNumero();
                            VistaSelect vistaSelect = new VistaSelect(vistaHome, pesebrera.getNumero(), i, j);
                            vistaSelect.setVisible(true);
                            this.dispose();
                        } else {
                            VistaGestionAnimales vistaGestionAnimales = new VistaGestionAnimales(vistaHome, pesebrera.getNumero(), i, j);
                            vistaGestionAnimales.setVisible(true);
                            this.dispose();
                        }
                    }
                }
            }
        }
    }
}
