/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.awt.AWTUtilities;
import excepciones.PersonaYaRegistradaException;
import excepciones.PesoNoValidoException;
import excepciones.RazonNoSeleccionadaException;
import java.awt.Frame;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Animal;
import modelo.Porcino;
import modelo.RazonEliminacion;
import modelo.pila.AccionRealizadaEliminacion;

/**
 *
 * @author andre
 */
public class VistaFormularioEliminar extends javax.swing.JDialog {

    VistaHome vistaHome;
    Animal animal;

    /**
     * Creates new form VistaFormularioEliminar
     */
    public VistaFormularioEliminar(java.awt.Frame parent, boolean modal, VistaHome vistaHome, Animal animal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);
        this.vistaHome = vistaHome;
        this.animal = animal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcbRazonEliminacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnFondoDark.png"))); // NOI18N
        jButton3.setText("Aceptar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnFondoDark_Pressed.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 110, 35));

        jLabel3.setFont(new java.awt.Font("Duralith", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Razón de Eliminación");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jcbRazonEliminacion.setBackground(new java.awt.Color(255, 255, 255));
        jcbRazonEliminacion.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        jcbRazonEliminacion.setForeground(new java.awt.Color(0, 0, 0));
        jcbRazonEliminacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Muerte por Enfermedad", "Muerte para Consumo", "Venta", "Pérdida", "Otro" }));
        jcbRazonEliminacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbRazonEliminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRazonEliminacionActionPerformed(evt);
            }
        });
        jPanel1.add(jcbRazonEliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfaz_Eliminar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbRazonEliminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRazonEliminacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRazonEliminacionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (jcbRazonEliminacion.getSelectedIndex() == 0) {
                throw new RazonNoSeleccionadaException();
            }
            RazonEliminacion razon = null;
            if (jcbRazonEliminacion.getSelectedIndex() == 1) {
                razon = new RazonEliminacion(animal, "Muerte por Enfermedad");
            }
            if (jcbRazonEliminacion.getSelectedIndex() == 2) {
                razon = new RazonEliminacion(animal, "Muerte para Consumo");
            }
            if (jcbRazonEliminacion.getSelectedIndex() == 3) {
                razon = new RazonEliminacion(animal, "Venta");
                VistaFormularioVenta dialog = new VistaFormularioVenta(new javax.swing.JFrame(), true, vistaHome, animal);
                dialog.setVisible(true);
            }
            if (jcbRazonEliminacion.getSelectedIndex() == 4) {
                razon = new RazonEliminacion(animal, "Pérdida");
            }
            if (jcbRazonEliminacion.getSelectedIndex() == 5) {
                String razonEliminacion = JOptionPane.showInputDialog("Ingrese la razón de eliminación");
                razon = new RazonEliminacion(animal, razonEliminacion);
            }
            vistaHome.getControladorVYE().añadirRazonEliminar(razon);
            mostrarMensaje("Razón registrada Correctamente", "Information");
            this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            this.dispose();
//            System.exit(DISPOSE_ON_CLOSE);
        } catch (RazonNoSeleccionadaException ex) {
            mostrarMensaje(ex.getMessage(), "Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    int xx, xy;
    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    public void mostrarMensaje(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.ERROR_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoBlack_Pequeño.png")));
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaFormularioEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//	public void run() {
//		VistaFormularioEliminar dialog = new VistaFormularioEliminar(new javax.swing.JFrame(), true);
//		dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//			@Override
//			public void windowClosing(java.awt.event.WindowEvent e) {
//				System.exit(0);
//			}
//		});
//		dialog.setVisible(true);
//	}
//});
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbRazonEliminacion;
    // End of variables declaration//GEN-END:variables
}
