/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author andre
 */
public class VistaAdmin extends javax.swing.JFrame {

    VistaHome vistaHome;

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin(VistaHome vistaHome) {
        initComponents();
        setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);
        this.vistaHome = vistaHome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnveterinaria = new javax.swing.JButton();
        btnRegistrarUsuarios = new javax.swing.JButton();
        btnGestionEmpleados = new javax.swing.JButton();
        btnGestionPorcinos = new javax.swing.JButton();
        btnGestionBovinos = new javax.swing.JButton();
        btnGestionEquinos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Duralith", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOLA ADMIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btnveterinaria.setBackground(new java.awt.Color(255, 255, 255));
        btnveterinaria.setFont(new java.awt.Font("Duralith", 0, 14)); // NOI18N
        btnveterinaria.setForeground(new java.awt.Color(0, 0, 0));
        btnveterinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnveterinaria.setText("Veterinaria (Espectador)");
        btnveterinaria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnveterinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnveterinaria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnveterinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnveterinariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnveterinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 210, 35));

        btnRegistrarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarUsuarios.setFont(new java.awt.Font("Duralith", 0, 14)); // NOI18N
        btnRegistrarUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnRegistrarUsuarios.setText("Registrar Usuarios");
        btnRegistrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 35));

        btnGestionEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionEmpleados.setFont(new java.awt.Font("Duralith", 0, 14)); // NOI18N
        btnGestionEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnGestionEmpleados.setText("Gestionar Empleados");
        btnGestionEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestionEmpleados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 35));

        btnGestionPorcinos.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionPorcinos.setFont(new java.awt.Font("Duralith", 0, 14)); // NOI18N
        btnGestionPorcinos.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionPorcinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnGestionPorcinos.setText("Gestionar Pocilgas (Porcinos)");
        btnGestionPorcinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionPorcinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestionPorcinos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnGestionPorcinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPorcinosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionPorcinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 35));

        btnGestionBovinos.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionBovinos.setFont(new java.awt.Font("Duralith", 0, 14)); // NOI18N
        btnGestionBovinos.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionBovinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnGestionBovinos.setText("Gestionar Lotes (Bovinos)");
        btnGestionBovinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionBovinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestionBovinos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnGestionBovinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionBovinosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionBovinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 35));

        btnGestionEquinos.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionEquinos.setFont(new java.awt.Font("Duralith", 0, 14)); // NOI18N
        btnGestionEquinos.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionEquinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnGestionEquinos.setText("Gestionar Pesebreras (Equinos)");
        btnGestionEquinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionEquinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestionEquinos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnGestionEquinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEquinosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionEquinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoWhite_Pequeño.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 100, 80));

        jLabel4.setFont(new java.awt.Font("Duralith", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selecciona una acción a realizar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSalir.png"))); // NOI18N
        btnSalir.setToolTipText("Cerrar Sesión");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSalirPressed.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_ADMIN.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        vistaHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuariosActionPerformed
        VistaRegister vistaRegister = new VistaRegister(vistaHome);
        vistaRegister.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarUsuariosActionPerformed

    private void btnGestionBovinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionBovinosActionPerformed
        vistaHome.terreno = vistaHome.LOTE;
        abrirVentanaTerreno();
    }//GEN-LAST:event_btnGestionBovinosActionPerformed

    private void btnGestionPorcinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPorcinosActionPerformed
        vistaHome.terreno = vistaHome.POCILGA;
        abrirVentanaTerreno();
    }//GEN-LAST:event_btnGestionPorcinosActionPerformed

    private void btnGestionEquinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEquinosActionPerformed
        vistaHome.terreno = vistaHome.PESEBRERA;
        abrirVentanaTerreno();
    }//GEN-LAST:event_btnGestionEquinosActionPerformed

    private void btnveterinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnveterinariaActionPerformed
        VistaVeterinario vistaVeterinario = new VistaVeterinario(vistaHome);
        vistaVeterinario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnveterinariaActionPerformed

    private void btnGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosActionPerformed
        VistaGestionUsuarios vistaGestionUsuarios = new VistaGestionUsuarios(vistaHome);
        vistaGestionUsuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionEmpleadosActionPerformed

    private void abrirVentanaTerreno() {
        VistaTerreno vistaTerreno = new VistaTerreno(vistaHome);
        vistaTerreno.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionBovinos;
    private javax.swing.JButton btnGestionEmpleados;
    private javax.swing.JButton btnGestionEquinos;
    private javax.swing.JButton btnGestionPorcinos;
    private javax.swing.JButton btnRegistrarUsuarios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnveterinaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
